In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./combined_match_data.csv")
df.head()

,Unnamed: 0,Date,Tm,Opp,Result,MP,FG,FGA,FG%,2P,...,DRB%_players,TRB%_players,AST%_players,STL%_players,BLK%_players,TOV%_players,USG%_players,ORtg_players,DRtg_players,BPM_players
0,0,2021/3/13,ATL,SAC,W 121-106,0,0,-14,0.073,-5,...,-1.301826,-0.438604,-2.520396,0.207396,0.250382,-5.375500,-0.004035,24.143611,-17.373333,3.802056
1,1,2021/3/13,BRK,DET,W 100-95,0,3,-8,0.077,5,...,-3.157257,-2.747542,-3.111181,-0.421299,-0.536125,-2.824667,-0.006569,15.753750,-3.751111,1.236181
2,2,2021/3/13,CHO,TOR,W 114-104,0,2,-16,0.103,-4,...,-0.820924,0.832389,2.457729,0.017625,-1.344785,11.910583,0.004181,5.725833,-8.543819,2.238097
3,3,2021/3/13,DAL,DEN,W 116-103,0,5,-4,0.077,3,...,0.484389,1.324847,-3.099299,-0.020514,0.727271,-2.464722,-0.025951,26.161597,-15.609375,3.348806
4,4,2021/3/13,MIN,POR,L 121-125,0,1,-3,0.029,4,...,5.075958,4.888764,-2.418979,-0.221194,1.184958,10.364042,0.011271,-2.641875,4.036528,-0.933243

In [3]:
# calculate A/T, efficiency(EFF) and EFFECTIVE FIELD GOAL PERCENTAGE 
df["A/T"] = df["AST_players"]/df["TOV_players"]
df["EFF"] = df["PTS_players"]+df["TRB_players"]+df["AST_players"]+df["STL_players"]+df["BLK_players"]
-(df["FGA_players"]-df["FG_players"])-(df["FTA_players"]-df["FT_players"])-df["TOV_players"]
df.head()

,Unnamed: 0,Date,Tm,Opp,Result,MP,FG,FGA,FG%,2P,...,AST%_players,STL%_players,BLK%_players,TOV%_players,USG%_players,ORtg_players,DRtg_players,BPM_players,A/T,EFF
0,0,2021/3/13,ATL,SAC,W 121-106,0,0,-14,0.073,-5,...,-2.520396,0.207396,0.250382,-5.375500,-0.004035,24.143611,-17.373333,3.802056,1.324446,-4.153194
1,1,2021/3/13,BRK,DET,W 100-95,0,3,-8,0.077,5,...,-3.111181,-0.421299,-0.536125,-2.824667,-0.006569,15.753750,-3.751111,1.236181,0.528696,1.059306
2,2,2021/3/13,CHO,TOR,W 114-104,0,2,-16,0.103,-4,...,2.457729,0.017625,-1.344785,11.910583,0.004181,5.725833,-8.543819,2.238097,0.486039,0.533194
3,3,2021/3/13,DAL,DEN,W 116-103,0,5,-4,0.077,3,...,-3.099299,-0.020514,0.727271,-2.464722,-0.025951,26.161597,-15.609375,3.348806,0.809791,2.377222
4,4,2021/3/13,MIN,POR,L 121-125,0,1,-3,0.029,4,...,-2.418979,-0.221194,1.184958,10.364042,0.011271,-2.641875,4.036528,-0.933243,-0.533985,-0.239583

In [4]:
df.shape

(600, 68)

In [5]:
df.to_csv('./combined_match_data_features.csv', index = 0)